package no.knowit.seam.model;

// Generated 08.des.2009 12:44:37 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "movie", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
public class Movie implements java.io.Serializable {

	private static final long serialVersionUID = 1515968741131218968L;
	
	private Integer id;
	private Long version;
	private String director;
	private String title;
	private Integer year;

	public Movie() {
	}

	public Movie(String director, String title, Integer year) {
		this.director = director;
		this.title = title;
		this.year = year;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(length=60, name = "director")
	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	@Column(length=60, name = "title", unique = true)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

}
