package no.knowit.openejbtest.model;

// Generated 08.des.2009 12:44:37 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Version;

import org.hibernate.validator.NotEmpty;
import org.hibernate.validator.NotNull;

/**
 * Movie generated by hbm2java
 */
@Entity
public class Movie implements java.io.Serializable {

	private static final long serialVersionUID = 1515968741131218968L;
	
	private Integer id;
	private Long version;
	private String director;
	private String title;
	private Integer year;

	public Movie() {
	}

	public Movie(String director, String title, Integer year) {
		this.director = director;
		this.title = title;
		this.year = year;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(length=50, nullable=false)
	@NotEmpty
	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	@Column(length=60, unique = true, nullable=false)
	@NotEmpty
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(nullable=false)
	@NotNull 
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}
}
